tap "homebrew/bundle"
tap "homebrew/services"

brew "mas"
brew "gh"
brew "git"
brew "git-lfs"
brew "git-delta"
brew "zsh"
brew "bat"
brew "ripgrep"
brew "fzf"
brew "jq"
brew "curl"
brew "asdf"
brew "pyenv"
brew "zplug"

cask "iterm2"
cask "google-chrome"
cask "visual-studio-code"
cask "jetbrains-toolbox"
cask "raycast"
cask "bitwarden"
cask "notion"
cask "rectangle"
cask "slack"
cask "dbeaver-community"
cask "discord"
cask "zoom"
cask "brave-browser"
cask "devtoys"

mas "RunCat", id: 1429033973
mas "Amphetamine", id: 937984704
mas "KakaoTalk", id: 869223134
