#!/usr/bin/env bash

if test ! $(which brew); then
    echo "Install homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew bundle

printf '\n Done...'